Update patch set 1
Patch Set 1:

Hum, weird failure in koji, extract from build.log:

+ cd gerrit-2.11.10
+ sed -i 's/import subprocess/return '\''v2.11.10'\''/' tools/git.defs
+ sed -i 's/git describe HEAD/echo v2.11.10/' tools/default.defs
+ buck build release
Not using buckd because watchman isn't installed.
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[-] PARSING BUCK FILES...FINISHED 2.0s
Not using buckd because watchman isn't installed.
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
[-] PARSING BUCK FILES...FINISHED 2.3s
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
BUILD FAILED: //Documentation:html_htmlonly failed with exit code 137:
genrule
[-] BUILDING...FINISHED 400.1s
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.ZAbduM (%build)
    Bad exit status from /var/tmp/rpm-tmp.ZAbduM (%build)
Child return code was: 1

Patch-set: 1